import RequestProject.MaskData

/-!
# Computable enumeration of a truncated numerical semigroup

The masks used in Sections 3 and 4.3 of `masked_digit_bound.tex` are truncations
`M = ⟨g₁, …, g₆⟩ ∩ [0, B]` of numerical semigroups, and the source records the discrete data
`|M|`, `|M + M|`, `|M − M|` and `κ(1)` obtained by enumerating them.

This file provides the enumeration in a form Lean can evaluate: a dynamic-programming table
`semiArr` for membership in the numerical semigroup, together with the proof that it computes
membership in the additive closure, and computable lists representing the mask, its sum
support and its difference support.  The cardinalities recorded in equations (10)
(`eq:counts`) of `masked_digit_bound.tex` and in Section 4.3 are then discharged by
evaluation.
-/

open scoped BigOperators

namespace MaskedDigit

/-! ## The truncated numerical semigroup -/

open Classical in
/-- The numerical semigroup generated by `gens`, truncated to `[0, B]`.  This is the
truncation `⟨g₁, …, g₆⟩ ∩ [0, B]` used throughout `masked_digit_bound.tex`. -/
noncomputable def generatedUpTo (gens : Finset ℕ) (B : ℕ) : Finset ℕ :=
  (Finset.range (B + 1)).filter fun n => n ∈ AddSubmonoid.closure (gens : Set ℕ)

theorem mem_generatedUpTo {gens : Finset ℕ} {B n : ℕ} :
    n ∈ generatedUpTo gens B ↔ n ≤ B ∧ n ∈ AddSubmonoid.closure (gens : Set ℕ) := by
  simp [generatedUpTo]

/-- The recursive characterization of membership in a numerical semigroup that underlies the
dynamic program: a positive `n` lies in `⟨gens⟩` iff some positive generator `g ≤ n` can be
subtracted from it. -/
theorem mem_closure_list_succ {gens : List ℕ} {n : ℕ} (hn : 0 < n) :
    n ∈ AddSubmonoid.closure {x : ℕ | x ∈ gens} ↔
      ∃ g ∈ gens, 0 < g ∧ g ≤ n ∧ (n - g) ∈ AddSubmonoid.closure {x : ℕ | x ∈ gens} := by
  constructor
  · intro h
    obtain ⟨l, hl, hsum⟩ := AddSubmonoid.exists_list_of_mem_closure h
    have hex : ∃ g ∈ l, 0 < g := by
      by_contra hc
      push_neg at hc
      have : l.sum = 0 := by
        have : ∀ x ∈ l, x = 0 := fun x hx => Nat.le_zero.1 (hc x hx)
        simpa using List.sum_eq_zero this
      omega
    obtain ⟨g, hgl, hg0⟩ := hex
    obtain ⟨l₁, l₂, rfl⟩ := List.mem_iff_append.1 hgl
    refine ⟨g, hl g hgl, hg0, ?_, ?_⟩
    · simp at hsum; omega
    · have hrest : ((l₁ ++ l₂).sum) = n - g := by simp at hsum ⊢; omega
      rw [← hrest]
      exact AddSubmonoid.list_sum_mem _ fun x hx =>
        AddSubmonoid.subset_closure (hl x (by simp at hx ⊢; tauto))
  · rintro ⟨g, hg, hg0, hgn, hrest⟩
    have hsplit : n = g + (n - g) := by omega
    rw [hsplit]
    exact AddSubmonoid.add_mem _ (AddSubmonoid.subset_closure hg) hrest

/-! ## The dynamic-programming table -/

/-- The dynamic-programming table for membership in the numerical semigroup generated by
`gens`: `semiArr gens n` is an array of length `n + 1` whose `i`-th entry records whether
`i ∈ ⟨gens⟩`. -/
def semiStep (gens : List ℕ) (prev : Array Bool) (j : ℕ) : Array Bool :=
  prev.push (gens.any fun g => 0 < g && g ≤ j + 1 && prev.getD (j + 1 - g) false)

def semiArr (gens : List ℕ) (n : ℕ) : Array Bool :=
  (List.range n).foldl (semiStep gens) #[true]

theorem semiArr_zero (gens : List ℕ) : semiArr gens 0 = #[true] := rfl

theorem semiArr_succ (gens : List ℕ) (n : ℕ) :
    semiArr gens (n + 1) =
      (semiArr gens n).push
        (gens.any fun g => 0 < g && g ≤ n + 1 && (semiArr gens n).getD (n + 1 - g) false) := by
  simp [semiArr, List.range_succ, semiStep]

theorem semiArr_size (gens : List ℕ) : ∀ n, (semiArr gens n).size = n + 1
  | 0 => rfl
  | n + 1 => by rw [semiArr_succ]; simp [semiArr_size gens n]

private theorem push_getD_lt (a : Array Bool) (x : Bool) (i : ℕ) (h : i < a.size) :
    (a.push x).getD i false = a.getD i false := by
  simp only [Array.getD, Array.size_push, dif_pos h, dif_pos (Nat.lt_succ_of_lt h)]
  exact Array.getElem_push_lt _

private theorem push_getD_size (a : Array Bool) (x : Bool) (i : ℕ) (h : i = a.size) :
    (a.push x).getD i false = x := by
  subst h; simp [Array.getD, Array.size_push]

theorem semiArr_getD_of_le (gens : List ℕ) {i n : ℕ} (h : i ≤ n) :
    ∀ m, n ≤ m → (semiArr gens m).getD i false = (semiArr gens n).getD i false := by
  intro m
  induction m with
  | zero =>
      intro hm
      have : n = 0 := by omega
      subst this; rfl
  | succ k ih =>
      intro hm
      rcases Nat.eq_or_lt_of_le hm with he | hlt
      · rw [← he]
      · have hnk : n ≤ k := by omega
        rw [semiArr_succ, push_getD_lt _ _ _ (by rw [semiArr_size]; omega), ih hnk]

theorem semiArr_getD_top (gens : List ℕ) (n : ℕ) :
    (semiArr gens (n + 1)).getD (n + 1) false =
      (gens.any fun g => 0 < g && g ≤ n + 1 && (semiArr gens n).getD (n + 1 - g) false) := by
  rw [semiArr_succ]
  exact push_getD_size _ _ _ (by rw [semiArr_size])

theorem semiArr_getD_of_gt (gens : List ℕ) {n i : ℕ} (h : n < i) :
    (semiArr gens n).getD i false = false := by
  have : ¬ i < (semiArr gens n).size := by rw [semiArr_size]; omega
  simp [Array.getD, this]

/-- **Correctness of the dynamic program**: for `i ≤ n`, the `i`-th entry of the table is
`true` exactly when `i` belongs to the numerical semigroup generated by `gens`. -/
theorem semiArr_getD_iff (gens : List ℕ) :
    ∀ i, ∀ n, i ≤ n →
      ((semiArr gens n).getD i false = true ↔ i ∈ AddSubmonoid.closure {x : ℕ | x ∈ gens}) := by
  intro i
  induction i using Nat.strong_induction_on with
  | _ i ih =>
    intro n hin
    rcases Nat.eq_zero_or_pos i with rfl | hi
    · rw [semiArr_getD_of_le gens (Nat.zero_le _) n hin]
      simp [semiArr_zero, Array.getD]
    · obtain ⟨j, rfl⟩ : ∃ j, i = j + 1 := ⟨i - 1, by omega⟩
      rw [semiArr_getD_of_le gens (le_refl _) n hin, semiArr_getD_top,
        mem_closure_list_succ hi]
      simp only [List.any_eq_true, Bool.and_eq_true, decide_eq_true_eq]
      constructor
      · rintro ⟨g, hg, ⟨hg0, hgle⟩, hrest⟩
        refine ⟨g, hg, hg0, hgle, ?_⟩
        exact (ih (j + 1 - g) (by omega) j (by omega)).1 hrest
      · rintro ⟨g, hg, hg0, hgle, hrest⟩
        exact ⟨g, hg, ⟨hg0, hgle⟩, (ih (j + 1 - g) (by omega) j (by omega)).2 hrest⟩

/-- The table entry at an arbitrary index `i` decides membership in the truncated semigroup
`⟨gens⟩ ∩ [0, B]`. -/
theorem semiArr_getD_iff_mem (gens : List ℕ) (B i : ℕ) :
    ((semiArr gens B).getD i false = true ↔
      i ≤ B ∧ i ∈ AddSubmonoid.closure {x : ℕ | x ∈ gens}) := by
  rcases le_or_gt i B with h | h
  · rw [semiArr_getD_iff gens i B h]
    exact ⟨fun hm => ⟨h, hm⟩, fun hm => hm.2⟩
  · rw [semiArr_getD_of_gt gens h]
    simp only [Bool.false_eq_true, false_iff, not_and]
    intro hle; omega

/-! ## Computable lists for the mask, the sum support and the difference support -/

/-- The mask `M = ⟨gens⟩ ∩ [0, B]`, as a computable list. -/
def semiMask (gens : List ℕ) (B : ℕ) : List ℕ :=
  let t := semiArr gens B
  (List.range (B + 1)).filter fun n => t.getD n false

theorem mem_semiMask {gens : List ℕ} {B n : ℕ} :
    n ∈ semiMask gens B ↔ n ≤ B ∧ n ∈ AddSubmonoid.closure {x : ℕ | x ∈ gens} := by
  simp only [semiMask, List.mem_filter, List.mem_range]
  rw [semiArr_getD_iff_mem]
  constructor
  · rintro ⟨_, h⟩; exact h
  · rintro ⟨h1, h2⟩; exact ⟨by omega, h1, h2⟩

theorem semiMask_nodup (gens : List ℕ) (B : ℕ) : (semiMask gens B).Nodup :=
  (List.nodup_range).filter _

/-- The sum support `M + M`, as a computable list. -/
def semiSumList (gens : List ℕ) (B : ℕ) : List ℕ :=
  let t := semiArr gens B
  let ml := semiMask gens B
  (List.range (2 * B + 1)).filter fun s => ml.any fun a => a ≤ s && t.getD (s - a) false

theorem semiSumList_nodup (gens : List ℕ) (B : ℕ) : (semiSumList gens B).Nodup :=
  (List.nodup_range).filter _

/-- The index list of the difference support: the index `i` ranges over `[0, 2B]` and
represents the difference `d = i − B`. -/
def diffIdxList (gens : List ℕ) (B : ℕ) : List ℕ :=
  let t := semiArr gens B
  let ml := semiMask gens B
  (List.range (2 * B + 1)).filter fun i => ml.any fun a => i ≤ a + B && t.getD (a + B - i) false

/-- The difference support `M − M`, as a computable list of integers. -/
def semiDiffList (gens : List ℕ) (B : ℕ) : List ℤ :=
  List.map (fun i : ℕ => (i : ℤ) - (B : ℤ)) (diffIdxList gens B)

theorem semiDiffList_nodup (gens : List ℕ) (B : ℕ) : (semiDiffList gens B).Nodup := by
  refine List.Nodup.map ?_ ((List.nodup_range).filter _)
  intro a b hab
  simp only at hab
  have : (a : ℤ) = (b : ℤ) := by omega
  exact_mod_cast this

/-! ## The minimum witness cost of the difference one -/

/-- The computable check that no `a < a₀` has both `a` and `a − 1` in the mask.  Together
with a pair `a₀ − 1, a₀ ∈ M` this determines `κ(1) = 2a₀ − 1`, the value recorded in
Section 3 of `masked_digit_bound.tex`. -/
def noAdjacentBelow (gens : List ℕ) (B a0 : ℕ) : Bool :=
  let t := semiArr gens B
  (List.range a0).all fun a => !(decide (0 < a) && t.getD a false && t.getD (a - 1) false)

/-- If `a₀ − 1, a₀ ∈ M` and no smaller pair of adjacent elements exists, then the minimum
witness cost of the difference one is `κ(1) = 2a₀ − 1`. -/
theorem kappa_one_eq {gens : List ℕ} {gensF : Finset ℕ}
    (D : MaskData) (h : (gensF : Set ℕ) = {x : ℕ | x ∈ gens})
    (hM : D.M = generatedUpTo gensF D.B) (a0 : ℕ) (ha0 : 0 < a0) (ha : a0 ∈ D.M)
    (ha1 : a0 - 1 ∈ D.M) (hchk : noAdjacentBelow gens D.B a0 = true) :
    D.kappa 1 = 2 * a0 - 1 := by
  have hmem : ∀ a : ℕ, a ∈ D.M ↔ (semiArr gens D.B).getD a false = true := by
    intro a
    rw [hM, mem_generatedUpTo, h, semiArr_getD_iff_mem]
  have hcast : ((a0 : ℤ) - ((a0 - 1 : ℕ) : ℤ)) = 1 := by
    have : ((a0 - 1 : ℕ) : ℤ) = (a0 : ℤ) - 1 := by
      rw [Nat.cast_sub ha0]; norm_num
    rw [this]; ring
  have hupper : D.kappa 1 ≤ 2 * a0 - 1 := by
    have := D.kappa_le ha ha1 hcast
    omega
  have hone : (1 : ℤ) ∈ D.diffSupport := D.mem_diffSupport.2 ⟨a0, ha, a0 - 1, ha1, hcast⟩
  obtain ⟨a, haM, b, hbM, hab, hsum⟩ := D.exists_min_witness hone
  have hba : b + 1 = a := by omega
  have hapos : 0 < a := by omega
  have hage : a0 ≤ a := by
    by_contra hlt
    push_neg at hlt
    have hall := List.all_eq_true.1 hchk a (List.mem_range.2 hlt)
    have h1 : (semiArr gens D.B).getD a false = true := (hmem a).1 haM
    have h2 : (semiArr gens D.B).getD (a - 1) false = true := by
      have : a - 1 = b := by omega
      rw [this]; exact (hmem b).1 hbM
    simp [h1, h2, hapos] at hall
  omega

/-! ## Bridging the abstract definitions to the computable lists -/

variable {gens : List ℕ} {gensF : Finset ℕ}

theorem generatedUpTo_eq (h : (gensF : Set ℕ) = {x : ℕ | x ∈ gens}) (B : ℕ) :
    generatedUpTo gensF B = (semiMask gens B).toFinset := by
  ext n
  simp only [List.mem_toFinset, mem_semiMask, mem_generatedUpTo, h]

theorem generatedUpTo_card (h : (gensF : Set ℕ) = {x : ℕ | x ∈ gens}) (B : ℕ) :
    (generatedUpTo gensF B).card = (semiMask gens B).length := by
  rw [generatedUpTo_eq h, List.toFinset_card_of_nodup (semiMask_nodup gens B)]

section Mask

variable (D : MaskData)

/-- If the mask of `D` is the truncated semigroup `⟨gens⟩ ∩ [0, B]`, the sum support `M + M`
of `masked_digit_bound.tex` is enumerated by `semiSumList`. -/
theorem sumSupport_eq (h : (gensF : Set ℕ) = {x : ℕ | x ∈ gens})
    (hM : D.M = generatedUpTo gensF D.B) :
    D.sumSupport = (semiSumList gens D.B).toFinset := by
  have hmem : ∀ a : ℕ, a ∈ D.M ↔ (a ≤ D.B ∧ a ∈ AddSubmonoid.closure {x : ℕ | x ∈ gens}) := by
    intro a; rw [hM, mem_generatedUpTo, h]
  ext s
  simp only [List.mem_toFinset, semiSumList, List.mem_filter, List.mem_range,
    List.any_eq_true, Bool.and_eq_true, decide_eq_true_eq, D.mem_sumSupport]
  constructor
  · rintro ⟨a, ha, b, hb, rfl⟩
    have ha' := (hmem a).1 ha
    have hb' := (hmem b).1 hb
    refine ⟨by omega, a, mem_semiMask.2 ha', by omega, ?_⟩
    rw [semiArr_getD_iff_mem]
    simpa [Nat.add_sub_cancel_left] using hb'
  · rintro ⟨-, a, ha, hle, hb⟩
    rw [semiArr_getD_iff_mem] at hb
    exact ⟨a, (hmem a).2 (mem_semiMask.1 ha), s - a, (hmem _).2 hb, by omega⟩

/-- If the mask of `D` is the truncated semigroup `⟨gens⟩ ∩ [0, B]`, the difference support
`M − M` of `masked_digit_bound.tex` is enumerated by `semiDiffList`. -/
theorem diffSupport_eq (h : (gensF : Set ℕ) = {x : ℕ | x ∈ gens})
    (hM : D.M = generatedUpTo gensF D.B) :
    D.diffSupport = (semiDiffList gens D.B).toFinset := by
  have hmem : ∀ a : ℕ, a ∈ D.M ↔ (a ≤ D.B ∧ a ∈ AddSubmonoid.closure {x : ℕ | x ∈ gens}) := by
    intro a; rw [hM, mem_generatedUpTo, h]
  ext d
  simp only [List.mem_toFinset, semiDiffList, diffIdxList, List.mem_map, List.mem_filter,
    List.mem_range, List.any_eq_true, Bool.and_eq_true, decide_eq_true_eq, D.mem_diffSupport]
  constructor
  · rintro ⟨a, ha, b, hb, rfl⟩
    have ha' := (hmem a).1 ha
    have hb' := (hmem b).1 hb
    have hba : b ≤ a + D.B := by omega
    refine ⟨a + D.B - b, ⟨by omega, a, mem_semiMask.2 ha', by omega, ?_⟩, ?_⟩
    swap
    · rw [Nat.cast_sub hba]
      push_cast
      ring
    rw [semiArr_getD_iff_mem]
    have : a + D.B - (a + D.B - b) = b := by omega
    rw [this]; exact hb'
  · rintro ⟨i, ⟨-, a, ha, hle, hb⟩, rfl⟩
    rw [semiArr_getD_iff_mem] at hb
    refine ⟨a, (hmem a).2 (mem_semiMask.1 ha), a + D.B - i, (hmem _).2 hb, ?_⟩
    have hai : (i : ℤ) ≤ (a : ℤ) + (D.B : ℤ) := by exact_mod_cast hle
    have : ((a + D.B - i : ℕ) : ℤ) = (a : ℤ) + (D.B : ℤ) - (i : ℤ) := by
      push_cast [Nat.cast_sub hle]; ring
    rw [this]; ring

theorem sumSupport_card (h : (gensF : Set ℕ) = {x : ℕ | x ∈ gens})
    (hM : D.M = generatedUpTo gensF D.B) :
    D.sumSupport.card = (semiSumList gens D.B).length := by
  rw [sumSupport_eq D h hM, List.toFinset_card_of_nodup (semiSumList_nodup gens D.B)]

theorem diffSupport_card (h : (gensF : Set ℕ) = {x : ℕ | x ∈ gens})
    (hM : D.M = generatedUpTo gensF D.B) :
    D.diffSupport.card = (semiDiffList gens D.B).length := by
  rw [diffSupport_eq D h hM, List.toFinset_card_of_nodup (semiDiffList_nodup gens D.B)]

end Mask


/-! ## Witness costs for the difference support

Section 3 of `masked_digit_bound.tex` evaluates `P₋(x) = ∑_{d ∈ D} x^{κ(d)}`.  For a *lower*
bound on `P₋` at a fugacity `x < 1` it suffices to replace each `κ(d)` by the cost `a + b` of
*some* witness pair `a, b ∈ M` with `a − b = d`, since `κ(d) ≤ a + b`.  Scanning the mask in
increasing order produces the cheapest witness, so no accuracy is lost. -/

/-- The witness `a ∈ M` of smallest value with `a + B − i ∈ M`, for the difference
`d = i − B`; the accompanying witness is `b = a + B − i`. -/
def diffWitnessAt (t : Array Bool) (ml : List ℕ) (B i : ℕ) : ℕ :=
  ((ml.find? fun a => decide (i ≤ a + B) && t.getD (a + B - i) false).getD 0)

/-- The list of witness costs `a + b`, one for each element of the difference support. -/
def diffCostList (gens : List ℕ) (B : ℕ) : List ℕ :=
  let t := semiArr gens B
  let ml := semiMask gens B
  (diffIdxList gens B).map fun i =>
    let a := diffWitnessAt t ml B i
    a + (a + B - i)

/-- The computable check that every chosen witness really is a pair of mask elements with the
prescribed difference. -/
def diffCostOK (gens : List ℕ) (B : ℕ) : Bool :=
  let t := semiArr gens B
  let ml := semiMask gens B
  (diffIdxList gens B).all fun i =>
    let a := diffWitnessAt t ml B i
    decide (i ≤ a + B) && t.getD a false && t.getD (a + B - i) false

theorem diffCostOK_spec {gens : List ℕ} {B : ℕ} (hok : diffCostOK gens B = true)
    {i : ℕ} (hi : i ∈ diffIdxList gens B) :
    i ≤ diffWitnessAt (semiArr gens B) (semiMask gens B) B i + B ∧
    (semiArr gens B).getD (diffWitnessAt (semiArr gens B) (semiMask gens B) B i) false = true ∧
    (semiArr gens B).getD
      (diffWitnessAt (semiArr gens B) (semiMask gens B) B i + B - i) false = true := by
  have := List.all_eq_true.1 hok i hi
  simpa [Bool.and_eq_true, decide_eq_true_eq, and_assoc] using this

/-- Every witness cost is at most `2B`, since both witnesses lie in `M ⊆ [0, B]`. -/
theorem diffCostList_le {gens : List ℕ} {B : ℕ} (hok : diffCostOK gens B = true) :
    ∀ c ∈ diffCostList gens B, c ≤ 2 * B := by
  intro c hc
  simp only [diffCostList, List.mem_map] at hc
  obtain ⟨i, hi, rfl⟩ := hc
  obtain ⟨h1, h2, h3⟩ := diffCostOK_spec hok hi
  have ha := (semiArr_getD_iff_mem gens B _).1 h2
  have hb := (semiArr_getD_iff_mem gens B _).1 h3
  omega

/-- Every element of the sum support is at most `2B`. -/
theorem semiSumList_le {gens : List ℕ} {B : ℕ} : ∀ s ∈ semiSumList gens B, s ≤ 2 * B := by
  intro s hs
  simp only [semiSumList, List.mem_filter, List.mem_range] at hs
  omega

section Partition

variable {gens : List ℕ} {gensF : Finset ℕ} (D : MaskData)

/-- The sum-side partition polynomial `P₊(x) = ∑_{s ∈ S} xˢ` of equation (4) of
`masked_digit_bound.tex`, as a sum over the computable enumeration of `S = M + M`. -/
theorem Pplus_eq_sumList (h : (gensF : Set ℕ) = {x : ℕ | x ∈ gens})
    (hM : D.M = generatedUpTo gensF D.B) (x : ℝ) :
    D.Pplus x = ((semiSumList gens D.B).map fun s => x ^ s).sum := by
  rw [MaskData.Pplus, sumSupport_eq D h hM,
    List.sum_toFinset _ (semiSumList_nodup gens D.B)]

/-- The mask list is strictly increasing, so scanning it with `List.find?` returns the
*smallest* admissible witness. -/
theorem semiMask_pairwise_lt (gens : List ℕ) (B : ℕ) :
    (semiMask gens B).Pairwise (· < ·) :=
  List.Pairwise.filter _ List.pairwise_lt_range

theorem zero_mem_semiMask (gens : List ℕ) (B : ℕ) : 0 ∈ semiMask gens B :=
  mem_semiMask.2 ⟨Nat.zero_le _, zero_mem _⟩

/-- **Minimality of the scanned witness**: no mask element smaller than
`diffWitnessAt` admits the same difference. -/
theorem diffWitnessAt_min {gens : List ℕ} {B i : ℕ} (hok : diffCostOK gens B = true)
    (hi : i ∈ diffIdxList gens B) {a' : ℕ}
    (ha' : (semiArr gens B).getD a' false = true) (hle : i ≤ a' + B)
    (hb' : (semiArr gens B).getD (a' + B - i) false = true) :
    diffWitnessAt (semiArr gens B) (semiMask gens B) B i ≤ a' := by
  obtain ⟨h1, h2, h3⟩ := diffCostOK_spec hok hi
  have hmemA : a' ∈ semiMask gens B :=
    mem_semiMask.2 ((semiArr_getD_iff_mem gens B a').1 ha')
  have hpa' : (decide (i ≤ a' + B) && (semiArr gens B).getD (a' + B - i) false) = true := by
    simp [hle, hb']
  rcases hf : (semiMask gens B).find?
      (fun a => decide (i ≤ a + B) && (semiArr gens B).getD (a + B - i) false) with _ | w
  · exfalso
    have hnone := List.find?_eq_none.1 hf
    have hzero := hnone 0 (zero_mem_semiMask gens B)
    rw [diffWitnessAt, hf] at h1 h3
    simp only [Option.getD_none] at h1 h3
    have hp0 : (decide (i ≤ 0 + B) && (semiArr gens B).getD (0 + B - i) false) = true := by
      rw [Bool.and_eq_true, decide_eq_true_eq]
      exact ⟨h1, h3⟩
    exact hzero hp0
  · have hval : diffWitnessAt (semiArr gens B) (semiMask gens B) B i = w := by
      rw [diffWitnessAt, hf]; rfl
    rw [hval]
    obtain ⟨hpw, as, bs, hsplit, hbefore⟩ := List.find?_eq_some_iff_append.1 hf
    have hpair := semiMask_pairwise_lt gens B
    rw [hsplit] at hpair hmemA
    rw [List.pairwise_append] at hpair
    obtain ⟨-, hpw2, hcross⟩ := hpair
    rcases List.mem_append.1 hmemA with hin | hin
    · exfalso
      have hb := hbefore a' hin
      rw [Bool.not_eq_true'] at hb
      simp only [Bool.and_eq_false_iff, decide_eq_false_iff_not, not_le] at hb
      rcases hb with hb | hb
      · omega
      · rw [hb'] at hb
        exact Bool.noConfusion hb
    · rcases List.mem_cons.1 hin with rfl | hin2
      · exact le_refl _
      · exact le_of_lt (List.rel_of_pairwise_cons hpw2 hin2)

/-- **The scanned witness cost is exactly `κ(d)`** for `d = i − B`, the minimum witness cost
of equation (3) of `masked_digit_bound.tex`. -/
theorem kappa_eq_diffCost {gens : List ℕ} {gensF : Finset ℕ} (D : MaskData)
    (h : (gensF : Set ℕ) = {x : ℕ | x ∈ gens}) (hM : D.M = generatedUpTo gensF D.B)
    (hok : diffCostOK gens D.B = true) {i : ℕ} (hi : i ∈ diffIdxList gens D.B) :
    D.kappa ((i : ℤ) - (D.B : ℤ)) =
      diffWitnessAt (semiArr gens D.B) (semiMask gens D.B) D.B i +
        (diffWitnessAt (semiArr gens D.B) (semiMask gens D.B) D.B i + D.B - i) := by
  have hmem : ∀ a : ℕ, (semiArr gens D.B).getD a false = true ↔ a ∈ D.M := by
    intro a
    rw [hM, mem_generatedUpTo, h, semiArr_getD_iff_mem]
  obtain ⟨h1, h2, h3⟩ := diffCostOK_spec hok hi
  set w := diffWitnessAt (semiArr gens D.B) (semiMask gens D.B) D.B i with hw
  have hwM : w ∈ D.M := (hmem w).1 h2
  have hbM : w + D.B - i ∈ D.M := (hmem _).1 h3
  have hcast : ∀ a : ℕ, i ≤ a + D.B →
      ((a : ℤ) - ((a + D.B - i : ℕ) : ℤ)) = (i : ℤ) - (D.B : ℤ) := by
    intro a hai
    rw [Nat.cast_sub hai]; push_cast; ring
  have hupper : D.kappa ((i : ℤ) - (D.B : ℤ)) ≤ w + (w + D.B - i) :=
    D.kappa_le hwM hbM (hcast w h1)
  have hd : ((i : ℤ) - (D.B : ℤ)) ∈ D.diffSupport :=
    D.mem_diffSupport.2 ⟨w, hwM, w + D.B - i, hbM, hcast w h1⟩
  obtain ⟨a', ha'M, b', hb'M, hab, hsum⟩ := D.exists_min_witness hd
  have ha'B : a' ≤ D.B := D.digits_le a' ha'M
  have hb'B : b' ≤ D.B := D.digits_le b' hb'M
  have hb'eq : b' = a' + D.B - i := by omega
  have hile : i ≤ a' + D.B := by omega
  have hmin := diffWitnessAt_min hok hi ((hmem a').2 ha'M) hile
    (by rw [← hb'eq]; exact (hmem b').2 hb'M)
  omega

/-- **The difference-side partition polynomial as an explicit finite sum**: `P₋(x)` of
equation (4) of `masked_digit_bound.tex` equals the sum of `x^{cost}` over the enumerated
witness costs, which are exactly the values `κ(d)`. -/
theorem Pminus_eq_costSum {gens : List ℕ} {gensF : Finset ℕ} (D : MaskData)
    (h : (gensF : Set ℕ) = {x : ℕ | x ∈ gens}) (hM : D.M = generatedUpTo gensF D.B)
    (hok : diffCostOK gens D.B = true) (x : ℝ) :
    D.Pminus x = ((diffCostList gens D.B).map fun c => x ^ c).sum := by
  rw [MaskData.Pminus, diffSupport_eq D h hM,
    List.sum_toFinset _ (semiDiffList_nodup gens D.B), semiDiffList, List.map_map,
    diffCostList, List.map_map]
  refine List.map_congr_left ?_ ▸ rfl
  intro i hi
  simp only [Function.comp_apply]
  rw [kappa_eq_diffCost D h hM hok hi]

/-- **A certified lower bound for the difference-side partition polynomial** `P₋(x)` of
equation (4) of `masked_digit_bound.tex`: replacing each `κ(d)` by the cost of an explicit
witness pair can only decrease the sum, because `x ≤ 1`. -/
theorem costSum_le_Pminus (h : (gensF : Set ℕ) = {x : ℕ | x ∈ gens})
    (hM : D.M = generatedUpTo gensF D.B) {x : ℝ} (hx0 : 0 ≤ x) (hx1 : x ≤ 1)
    (hok : diffCostOK gens D.B = true) :
    ((diffCostList gens D.B).map fun c => x ^ c).sum ≤ D.Pminus x := by
  have hmem : ∀ a : ℕ, (semiArr gens D.B).getD a false = true → a ∈ D.M := by
    intro a ha
    have := (semiArr_getD_iff_mem gens D.B a).1 ha
    rw [hM, mem_generatedUpTo, h]
    exact this
  rw [MaskData.Pminus, diffSupport_eq D h hM,
    List.sum_toFinset _ (semiDiffList_nodup gens D.B), semiDiffList, List.map_map,
    diffCostList, List.map_map]
  refine List.sum_le_sum ?_
  intro i hi
  obtain ⟨h1, h2, h3⟩ := diffCostOK_spec hok hi
  set a := diffWitnessAt (semiArr gens D.B) (semiMask gens D.B) D.B i with hadef
  have haM : a ∈ D.M := hmem a h2
  have hbM : a + D.B - i ∈ D.M := hmem _ h3
  have hdiff : ((a : ℤ) - ((a + D.B - i : ℕ) : ℤ)) = (i : ℤ) - (D.B : ℤ) := by
    have : ((a + D.B - i : ℕ) : ℤ) = (a : ℤ) + (D.B : ℤ) - (i : ℤ) := by
      rw [Nat.cast_sub h1]; push_cast; ring
    rw [this]; ring
  have hkappa : D.kappa ((i : ℤ) - (D.B : ℤ)) ≤ a + (a + D.B - i) := D.kappa_le haM hbM hdiff
  simpa using pow_le_pow_of_le_one hx0 hx1 hkappa

end Partition

end MaskedDigit
